### ISSUE TITLE
Fix cycle-dom test failure

### ISSUE THREAD

**Issue by Widdershin** [Widdershin/cycle-restart#11]
```js
should catch events from many elements using DOM.select().events() ‣
Error: Uncaught AssertionError: "First" === "Second" (http://localhost:7357/7934/test/browser/page/tests-bundle.js:1365)Error: Uncaught AssertionError: "First" === "Blecond" (tests-bundle.js:1365)
    at tests-bundle.js:18415:21
    at Function._throws (tests-bundle.js:454:5)
    at Function.assert.doesNotThrow (tests-bundle.js:485:11)
    at AnonymousObserver._onNext (tests-bundle.js:18414:16)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (tests-bundle.js:3075:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (tests-bundle.js:3009:31)
    at AnonymousObserver.tryCatcher (tests-bundle.js:1351:31)
    at AutoDetachObserverPrototype.next (tests-bundle.js:12948:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (tests-bundle.js:3009:31)
```

**Comment by Widdershin** [comment]
So this test is checking that you can have two divs with a common class (e.g. `.clickable`), then do `.select('.clickable').events('click')` and then clicking on either element will fire an event. It almost seems like clicking the second element causes it to fire as if you clicked the first element.

This one has me scratching my head.

**Comment by Widdershin** [comment]
This test: https://github.com/Widdershin/cycle-dom/blob/history-api/test/browser/render.js#L395-L434

**Comment by Widdershin** [comment]
No longer necessary as `restartable` means we don't need any driver code changes.
